### PR TITLE
remove edit user details form, Form data changes Closes #236 and Closes #235

### LINKED ISSUE #235: Editing User Does not work
Editing Users does not do anything + Don't let users change their emails

### LINKED ISSUE #236: Room Details Text Changes
Be more specific in the input labels,

Change bed capacity to bed capacity per room
Price to Price Per Room ( Including / Excluding GST )

We might have to do double the work to sanitize the data otherwise

### PR DESCRIPTION
**Pull request by bodhisha**

### CODE REVIEW

File: src/components/Facilitator/AddRoom.js [hunk 1]
```diff
@@ -362,7 +362,7 @@ export default function AddRoom({ id }) {
                                 onChange={handleChange}
                                 type="text"
                                 required=""
-                                placeholder="Capacity"
+                                placeholder="Bed Capacity"
```
Comment (bodhish) [inline src/components/Facilitator/AddRoom.js]: Make it simple
```suggestion
                                placeholder="Number of Beds"
```

File: src/components/Facilitator/AddRoom.js [hunk 2]
```diff
@@ -352,7 +352,7 @@ export default function AddRoom({ id }) {
                             <label
                                 className="block text-sm text-gray-600 "
                                 htmlFor="cost">
-                                Bed Capacity
+                                Bed Capacity Per Room
```
Comment (bodhish) [inline src/components/Facilitator/AddRoom.js:352]: `label` and `htmlFor` are not matching. Please check the code.

**Review by nikhilnathr — APPROVED** [review]

File: src/components/Facilitator/AddRoom.js [hunk 3]
```diff
@@ -383,7 +383,7 @@ export default function AddRoom({ id }) {
                                 onChange={handleChange}
                                 type="text"
                                 required=""
```
Comment (bodhish) [inline src/components/Facilitator/AddRoom.js]: Please remove `required="" ` if you are validating the fields via js

**Review by bodhish — CHANGES_REQUESTED** [review]
